export { default as Home } from './Dashboard/home/Home';
export * from './Dashboard';
export { default as List } from './Dashboard/list/List';
export { default as Login } from './Dashboard/login/Login';
export { default as New } from './Dashboard/new/New';
export { default as Register } from './Dashboard/register/Register';
export { default as Single } from './Dashboard/single/Single';
export { default as GlobalRouter } from './GlobalRouter';
export { default as App } from './Landing/App';
export { default as style } from './Landing/style';
